{
    "id": "/create",
    "cmd": null,
    "cpus": 1,
    "mem": 512,
    "disk": 0,
    "gpus": 0,
    "instances": 0,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "nfs",
            "LIKE",
            "true"
        ]
    ],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/home",
                "hostPath": "/opt/homes/home",
                "mode": "RW"
            },
            {
                "containerPath": "/services",
                "hostPath": "/opt/homes/services",
                "mode": "RW"
            },
            {
                "containerPath": "/etc/ocf-create",
                "hostPath": "/opt/share/docker/secrets/create",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/create",
            "network": "BRIDGE",
            "portMappings": null,
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "portDefinitions": [],
    "upgradeStrategy": {
        "minimumHealthCapacity": 0,
        "maximumOverCapacity": 0
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
}
