{
    "id": "/rt",
    "cmd": null,
    "cpus": 0.1,
    "mem": 2048,
    "disk": 0,
    "gpus": 0,
    "instances": 3,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/opt/share/secrets/rt",
                "hostPath": "/opt/share/docker/secrets/rt",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/rt",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 0,
                    "servicePort": 10001,
                    "protocol": "tcp",
                    "name": "main",
                    "labels": {}
                }
            ],
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "healthChecks": [
        {
            "protocol": "COMMAND",
            "command": {
                "value": "test $(curl -s -o /dev/null -w '%{http_code}' -H 'Host: rt.ocf.berkeley.edu' http://$HOST:$PORT0/) -eq 401",
            },
            "delaySeconds": 15,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "portDefinitions": [
        {
            "port": 10001,
            "protocol": "tcp",
            "labels": {}
        }
    ],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
