{
    "id": "/rt",
    "cmd": null,
    "cpus": 0.1,
    "mem": 2048,
    "disk": 0,
    "gpus": 0,
    "instances": 3,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "acceptedResourceRoles": ['*'],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/opt/share/secrets/rt",
                "hostPath": "/opt/share/docker/secrets/rt",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/rt",
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        },
        "portMappings": [
            {
                "containerPort": 80,
                "hostPort": 0,
                "servicePort": 10001,
                "protocol": "tcp",
                "name": "main",
                "labels": {}
            }
        ]
    },
    "networks": [
        {
            "mode": "container/bridge"
        }
    ],
    "healthChecks": [
        {
            "protocol": "COMMAND",
            "command": {
                "value": "/opt/rt/healthcheck $HOST $PORT0",
            },
            "delaySeconds": 15,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
