{
    "id": "/templates",
    "cmd": null,
    "cpus": 0.1,
    "mem": 128,
    "disk": 0,
    "gpus": 0,
    "instances": 3,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        # TODO: add another category for servers -- we don't actually need
        # secrets, just don't want to land on a desktop
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "container": {
        "type": "DOCKER",
        "volumes": [],
        "docker": {
            "image": "docker.ocf.berkeley.edu/templates",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "containerPort": 8000,
                    "hostPort": 0,
                    "servicePort": 10007,
                    "protocol": "tcp",
                    "name": "main",
                    "labels": {}
                }
            ],
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "healthChecks": [
        {
            "path": "/",
            "protocol": "HTTP",
            "portIndex": 0,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ignoreHttp1xx": false
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "portDefinitions": [
        {
            "port": 10007,
            "protocol": "tcp",
            "labels": {}
        }
    ],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
