{
    "id": "/ocfweb/web",
    "cmd": null,
    "cpus": 1,
    "mem": 1024,
    "disk": 0,
    "gpus": 0,
    "instances": 3,
    "executor": "",
    "requirePorts": false,
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocfweb",
                "hostPath": "/opt/share/docker/secrets/ocfweb",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/ocfweb-web",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "containerPort": 8000,
                    "hostPort": 0,
                    "servicePort": 10002,
                    "protocol": "tcp",
                    "name": "main",
                    "labels": {}
                }
            ],
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "env": {
        "OCFWEB_TESTING": "0"
    },
    "healthChecks": [
        {
            "protocol": "TCP",
            "portIndex": 0,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ignoreHttp1xx": false
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "portDefinitions": [
        {
            "port": 10002,
            "protocol": "tcp",
            "labels": {}
        }
    ],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
}
