{
    "id": "/ircbot",
    "cmd": null,
    "cpus": 1,
    "mem": 512,
    "gpus": 0,
    "disk": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "acceptedResourceRoles": ['*'],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocf-ircbot",
                "hostPath": "/opt/share/docker/secrets/ircbot",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/ircbot",
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        },
        "portMappings": [
            {
                "containerPort": 8888,
                "hostPort": 0,
                "servicePort": 10005,
                "protocol": "tcp",
                "name": "main",
                "labels": {}
            }
        ]
    },
    "networks": [
        {
          "mode": "container/bridge"
        }
    ],
    "upgradeStrategy": {
        "minimumHealthCapacity": 0,
        "maximumOverCapacity": 0
    },
    "healthChecks": [
        {
            "path": "/",
            "protocol": "MESOS_HTTP",
            "portIndex": 0,
            "delaySeconds": 15,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ipProtocol": "IPv4",
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },

    # ircbot is special: we never want there to be any extra apps running
    "upgradeStrategy": {
        "minimumHealthCapacity": 0,
        "maximumOverCapacity": 0,
    },
}
