{
    "id": "/pma",
    "cmd": null,
    "cpus": 0.1,
    "mem": 1024,
    "disk": 0,
    "gpus": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "constraints": [],
    "container": {
        "type": "DOCKER",
        "volumes": [],
        "docker": {
            "image": "docker.ocf.berkeley.edu/pma",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "containerPort": 8000,
                    "hostPort": 0,
                    "servicePort": 10003,
                    "protocol": "tcp",
                    "name": "main",
                    "labels": {}
                }
            ],
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "healthChecks": [
        {
            "path": "/",
            "protocol": "HTTP",
            "portIndex": 0,
            "gracePeriodSeconds": 300,
            "intervalSeconds": 60,
            "timeoutSeconds": 20,
            "maxConsecutiveFailures": 3,
            "ignoreHttp1xx": false
        }
    ],
    "labels": {
        "HAPROXY_GROUP": "lb"
    },
    "portDefinitions": [
        {
            "port": 10003,
            "protocol": "tcp",
            "labels": {}
        }
    ],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
}
