{
    "id": "/slackbridge",
    "cmd": null,
    "cpus": 1,
    "mem": 512,
    "disk": 0,
    "gpus": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "acceptedResourceRoles": ['*'],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocf-slackbridge",
                "hostPath": "/opt/share/docker/secrets/slackbridge",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/slackbridge",
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        },
        "portMappings": []
    },
    "networks": [
        {
            "mode": "container/bridge"
        }
    ],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
