{
    "id": "/slackbridge",
    "cmd": null,
    "cpus": 1,
    "mem": 512,
    "disk": 0,
    "gpus": 0,
    "instances": 0,
    "executor": "",
    "requirePorts": false,
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocf-slackbridge",
                "hostPath": "/opt/share/docker/secrets/slackbridge",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/slackbridge",
            "network": "BRIDGE",
            "portMappings": null,
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "portDefinitions": [
        {
            "protocol": "tcp",
            "port": 10006,
            "labels": {},
        }
    ],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
}
