{
    "id": "/ocfweb/worker",
    "cmd": null,
    "cpus": 1,
    "mem": 128,
    "gpus": 0,
    "disk": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocfweb",
                "hostPath": "/opt/share/docker/secrets/ocfweb",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/ocfweb-worker",
            "network": "BRIDGE",
            "portMappings": null,
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "env": {
        "OCFWEB_TESTING": "0"
    },
    "portDefinitions": [],
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
}
