{
    "id": "/create/healthcheck",
    "cmd": "runsv services/healthcheck",
    "cpus": 0.1,
    "mem": 512,
    "disk": 0,
    "gpus": 0,
    "instances": 1,
    "executor": "",
    "requirePorts": false,
    "constraints": [
        [
            "secrets",
            "LIKE",
            "true"
        ],
    ],
    "container": {
        "type": "DOCKER",
        "volumes": [
            {
                "containerPath": "/etc/ocf-create",
                "hostPath": "/opt/share/docker/secrets/create",
                "mode": "RO"
            }
        ],
        "docker": {
            "image": "docker.ocf.berkeley.edu/create",
            "network": "BRIDGE",
            "portMappings": null,
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "portDefinitions": [],
    "upgradeStrategy": {
        "minimumHealthCapacity": 0,
        "maximumOverCapacity": 0
    },
    "maxLaunchDelaySeconds": 3600,
    "backoffFactor": 1.15,
    "backoffSeconds": 1,
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1,
    },
    "killSelection": 'YOUNGEST_FIRST',
    "unreachableStrategy": {
        "inactiveAfterSeconds": 300,
        "expungeAfterSeconds": 600,
    },
}
